"""migracion inicial

Revision ID: 082c0573b63e
Revises: 
Create Date: 2026-05-12 20:57:22.756118
"""
from alembic import op
import sqlalchemy as sa


revision = '082c0573b63e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('nombre_completo', sa.String(length=160), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('ultimo_acceso', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_usuarios_estado'), ['estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_usuarios_rol'), ['rol'], unique=False)
        batch_op.create_index(batch_op.f('ix_usuarios_username'), ['username'], unique=True)

    op.create_table('ventas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_venta_csv', sa.Integer(), nullable=False),
    sa.Column('fecha_venta', sa.Date(), nullable=False),
    sa.Column('hora_venta', sa.Time(), nullable=False),
    sa.Column('canal_venta', sa.String(length=40), nullable=False),
    sa.Column('sucursal', sa.String(length=120), nullable=False),
    sa.Column('region_sucursal', sa.String(length=80), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('nombre_cliente', sa.String(length=160), nullable=False),
    sa.Column('tipo_cliente', sa.String(length=80), nullable=False),
    sa.Column('segmento_cliente', sa.String(length=100), nullable=False),
    sa.Column('ciudad_cliente', sa.String(length=100), nullable=False),
    sa.Column('zona_cliente', sa.String(length=100), nullable=False),
    sa.Column('nombre_producto', sa.String(length=180), nullable=False),
    sa.Column('categoria_producto', sa.String(length=100), nullable=False),
    sa.Column('linea_producto', sa.String(length=120), nullable=False),
    sa.Column('presentacion', sa.String(length=80), nullable=False),
    sa.Column('origen_cafe', sa.String(length=80), nullable=False),
    sa.Column('tipo_tueste', sa.String(length=80), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('descuento_porcentaje', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('total_bruto', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_descuento', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_neto', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ventas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ventas_canal_venta'), ['canal_venta'], unique=False)
        batch_op.create_index(batch_op.f('ix_ventas_categoria_producto'), ['categoria_producto'], unique=False)
        batch_op.create_index(batch_op.f('ix_ventas_ciudad_cliente'), ['ciudad_cliente'], unique=False)
        batch_op.create_index(batch_op.f('ix_ventas_fecha_venta'), ['fecha_venta'], unique=False)
        batch_op.create_index(batch_op.f('ix_ventas_id_cliente'), ['id_cliente'], unique=False)
        batch_op.create_index(batch_op.f('ix_ventas_id_venta_csv'), ['id_venta_csv'], unique=True)
        batch_op.create_index(batch_op.f('ix_ventas_linea_producto'), ['linea_producto'], unique=False)
        batch_op.create_index(batch_op.f('ix_ventas_nombre_producto'), ['nombre_producto'], unique=False)
        batch_op.create_index(batch_op.f('ix_ventas_origen_cafe'), ['origen_cafe'], unique=False)
        batch_op.create_index(batch_op.f('ix_ventas_region_sucursal'), ['region_sucursal'], unique=False)
        batch_op.create_index(batch_op.f('ix_ventas_segmento_cliente'), ['segmento_cliente'], unique=False)
        batch_op.create_index(batch_op.f('ix_ventas_sucursal'), ['sucursal'], unique=False)
        batch_op.create_index(batch_op.f('ix_ventas_tipo_cliente'), ['tipo_cliente'], unique=False)
        batch_op.create_index(batch_op.f('ix_ventas_tipo_tueste'), ['tipo_tueste'], unique=False)
        batch_op.create_index(batch_op.f('ix_ventas_total_neto'), ['total_neto'], unique=False)
        batch_op.create_index(batch_op.f('ix_ventas_zona_cliente'), ['zona_cliente'], unique=False)

    op.create_table('bitacora_acceso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('fecha_hora', sa.DateTime(), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('accion', sa.String(length=80), nullable=False),
    sa.Column('detalle', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bitacora_acceso', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bitacora_acceso_fecha_hora'), ['fecha_hora'], unique=False)
        batch_op.create_index(batch_op.f('ix_bitacora_acceso_usuario_id'), ['usuario_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bitacora_acceso', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bitacora_acceso_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_bitacora_acceso_fecha_hora'))

    op.drop_table('bitacora_acceso')
    with op.batch_alter_table('ventas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ventas_zona_cliente'))
        batch_op.drop_index(batch_op.f('ix_ventas_total_neto'))
        batch_op.drop_index(batch_op.f('ix_ventas_tipo_tueste'))
        batch_op.drop_index(batch_op.f('ix_ventas_tipo_cliente'))
        batch_op.drop_index(batch_op.f('ix_ventas_sucursal'))
        batch_op.drop_index(batch_op.f('ix_ventas_segmento_cliente'))
        batch_op.drop_index(batch_op.f('ix_ventas_region_sucursal'))
        batch_op.drop_index(batch_op.f('ix_ventas_origen_cafe'))
        batch_op.drop_index(batch_op.f('ix_ventas_nombre_producto'))
        batch_op.drop_index(batch_op.f('ix_ventas_linea_producto'))
        batch_op.drop_index(batch_op.f('ix_ventas_id_venta_csv'))
        batch_op.drop_index(batch_op.f('ix_ventas_id_cliente'))
        batch_op.drop_index(batch_op.f('ix_ventas_fecha_venta'))
        batch_op.drop_index(batch_op.f('ix_ventas_ciudad_cliente'))
        batch_op.drop_index(batch_op.f('ix_ventas_categoria_producto'))
        batch_op.drop_index(batch_op.f('ix_ventas_canal_venta'))

    op.drop_table('ventas')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_username'))
        batch_op.drop_index(batch_op.f('ix_usuarios_rol'))
        batch_op.drop_index(batch_op.f('ix_usuarios_estado'))
        batch_op.drop_index(batch_op.f('ix_usuarios_email'))

    op.drop_table('usuarios')
    # ### end Alembic commands ###
